// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdO7qpSJ98s8TeoWgBsWFer8UsdZ3JvBk',
    appId: '1:733230278247:web:b8930bbc59a89c2e5296c2',
    messagingSenderId: '733230278247',
    projectId: 'employeeapp-4b2fb',
    authDomain: 'employeeapp-4b2fb.firebaseapp.com',
    storageBucket: 'employeeapp-4b2fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe0KSoM-sg_uszs62JVARpj3eRtRnigtM',
    appId: '1:733230278247:android:0e5315ef212c131b5296c2',
    messagingSenderId: '733230278247',
    projectId: 'employeeapp-4b2fb',
    storageBucket: 'employeeapp-4b2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKDfUOS9iJVSVDV5rFK5jtX-HTQ-lkCJM',
    appId: '1:733230278247:ios:a971dc12a02157515296c2',
    messagingSenderId: '733230278247',
    projectId: 'employeeapp-4b2fb',
    storageBucket: 'employeeapp-4b2fb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKDfUOS9iJVSVDV5rFK5jtX-HTQ-lkCJM',
    appId: '1:733230278247:ios:a971dc12a02157515296c2',
    messagingSenderId: '733230278247',
    projectId: 'employeeapp-4b2fb',
    storageBucket: 'employeeapp-4b2fb.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdO7qpSJ98s8TeoWgBsWFer8UsdZ3JvBk',
    appId: '1:733230278247:web:350a8371991bc2235296c2',
    messagingSenderId: '733230278247',
    projectId: 'employeeapp-4b2fb',
    authDomain: 'employeeapp-4b2fb.firebaseapp.com',
    storageBucket: 'employeeapp-4b2fb.firebasestorage.app',
  );
}
